data:
  id: dlwh/wikitext_103_detokenized
  cache_dir: "gs://levanter-data/tokenized/wiki-llama2/"
  tokenizer: "meta-llama/Llama-2-70b-hf"
model:
  type: llama
# TODO: uncomment this once we resolve the resource exhaustion issue
hf_checkpoint: "meta-llama/Llama-2-70b-hf"
second_hf_checkpoint: "meta-llama/Llama-2-13b-hf"

trainer:
  wandb:
    project: "levanter"
    tags: ["openwebtext", "llama", "mistral-medium"]

  mp: p=f32,c=bfloat16
  train_batch_size: 64  # set for v4-64 TPU
  num_train_steps: 2
  steps_per_eval: 1
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
  per_device_eval_parallelism: -1

alpha: 0.1