data:
  train_urls:
      - "gs://pubmed-mosaic/pubmed-sharded/pubmedRandomized_train.{1..128}-of-128.jsonl.gz"
  validation_urls:
      - "gs://pubmed-mosaic/pubmed-sharded/pubmedRandomized_val.{1..8}-of-8.jsonl.gz"
  cache_dir: "gs://pubmed-mosaic/tokenized/pubmed-sharded/"
model:
  hidden_dim: 1608
  num_heads: 24
  num_layers: 48
  seq_len: 1024
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
trainer:
  mp: p=f32,c=bfloat16
  learning_rate: 1E-4
  weight_decay: 0.1
  model_axis_size: 4
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8

  axis_resources:
    batch: "data"
    # ZERO-3
    # "embed": ResourceAxis.DATA,
    vocab: "model"
    mlp: "model"
    heads: "model"
  # ZERO-3
  #parameter_axis_resources:
  #  embed: "data"
