data:
  train_urls:
      - "gs://pubmed-mosaic/pubmed-sharded/pubmedRandomized_train.{1..128}-of-128.jsonl.gz"
  validation_urls:
      - "gs://pubmed-mosaic/pubmed-sharded/pubmedRandomized_val.{1..8}-of-8.jsonl.gz"
  cache_dir: "gs://pubmed-mosaic/tokenized/pubmed-sharded/"
model:
  type: gpt2
  hidden_dim: 1600
  num_heads: 25
  num_layers: 48
  seq_len: 1024

  gradient_checkpointing: true
trainer:
  wandb:
    project: "levanter"
    tags: [ "pubmed", "gpt2"]

  mp: p=f32,c=bfloat16
  model_axis_size: 2
  per_device_parallelism: 1
optimizer:
  learning_rate: 1E-4
