data:
  cache_dir: "gs://levanter-data/tokenized/MultiLegalPile_Wikipedia_Shuffled"
  tokenizer: "dlwh/multilegal_tokenizer"
model:
  hidden_dim: 1536
  num_heads: 24
  num_layers: 48
  seq_len: 2048
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
trainer:
  wandb:
    project: "levanter-legal"
    tags: ["gpt2", "multilegalpile_wiki"]

  mp: p=f32,c=bfloat16
  learning_rate: 1E-4
  weight_decay: 0.1
  model_axis_size: 1
  per_device_parallelism: 2
  per_device_eval_parallelism: 8
  max_train_steps: 50000

  axis_resources:
    batch: "data"
    vocab: "model" # [vocab, embed] -> sharded by vocab across the model axis
    mlp: "model"
    heads: "model"
  # ZERO-3
  parameter_axis_resources:
    embed: "data"
