data:
  id: dlwh/wikitext_103_detokenized
  tokenizer: "EleutherAI/gpt-neox-20b"
  cache_dir: "gs://levanter-data/tokenized/wiki-fast/"
# data:
#   cache_dir: "gs://levanter-data/tokenized/pile-old/"
#   tokenizer: "EleutherAI/gpt-neox-20b"
model:
  type: gpt2
  hidden_dim: 768
  num_heads: 12
  num_layers: 12
  seq_len: 1024
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true

initialize_from_hf: "gpt2"
use_hf_model_config: true

trainer:
  wandb:
    project: "locked"
  tracker:
    project: "levanter"
    tags: [ "openwebtext", "gpt2", "itest"]

  mp: p=f32,c=bfloat16
  model_axis_size: 1
  per_device_parallelism: -1

  train_batch_size: 32
  # this is deliberately very small for testing
  num_train_steps: 2000000
  steps_per_eval: 50
  max_eval_batches: 1
optimizer:
  learning_rate: 1E-7
  weight_decay: 0.1
  warmup: 0.01
