data:
  id: mozilla-foundation/common_voice_16_1
  cache_dir: "gs://audio-via/processed/cv-l3"
  name: "en"
  text_key: "sentence"
  train_split: "train"
  validation_split: "validation"
  tokenizer: "WillHeld/via-llama"
  processor: "openai/whisper-large-v3"
model:
  type: whisper
initialize_from_hf: "WillHeld/via-llama"
use_hf_model_config: true
trainer:
  tracker:
    - type: wandb
      project: "levanter"
      tags: [ "cv", "via"]

  steps_per_eval: 500
  mp: p=f32,c=bf16
  model_axis_size: 1
  per_device_parallelism: -1
  train_batch_size: 512
  num_train_steps: 4300
  checkpointer:
    base_path: gs://audio-via/levanter-tpu-via-cv/lev_checkpoints
    save_interval: 60m
optimizer:
  learning_rate: 5E-5
  #learning_rate: 3e-4
  weight_decay: 0.1
  warmup: 0.01
via_init: True
hf_save_steps: 500
